"""Mosquitto broker lifecycle management for the live demo.

The project spec calls for a Dockerised broker. Docker Desktop is a heavy
dependency for a single 400 KB binary, so we support both and prefer whichever
is available: a native Homebrew/apt `mosquitto` process, or a container. Either
way the rest of the pipeline only ever sees `host:port`.
"""
from __future__ import annotations

import shutil
import socket
import subprocess
import time
from pathlib import Path

from swarmdef.config import REPO_ROOT
from swarmdef.utils.logging import get_logger

log = get_logger("twin.broker")

BROKER_DIR = REPO_ROOT / "mosquitto"
CONF_PATH = BROKER_DIR / "mosquitto.conf"

CONF_TEMPLATE = """# Auto-generated by swarmdef.twin.broker -- local demo broker only.
listener {port} {host}
allow_anonymous true
max_queued_messages 100000
max_inflight_messages 200
persistence false
log_dest stdout
log_type warning
log_type error
"""


def port_open(host: str = "127.0.0.1", port: int = 1883, timeout: float = 0.5) -> bool:
    """True if something is already accepting connections on host:port."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(timeout)
        return s.connect_ex((host, port)) == 0


def mosquitto_binary() -> str | None:
    """Locate the mosquitto broker executable, including Homebrew's sbin."""
    found = shutil.which("mosquitto")
    if found:
        return found
    for candidate in (
        "/opt/homebrew/opt/mosquitto/sbin/mosquitto",
        "/usr/local/opt/mosquitto/sbin/mosquitto",
        "/usr/sbin/mosquitto",
    ):
        if Path(candidate).exists():
            return candidate
    return None


def write_config(host: str = "127.0.0.1", port: int = 1883) -> Path:
    BROKER_DIR.mkdir(parents=True, exist_ok=True)
    CONF_PATH.write_text(CONF_TEMPLATE.format(host=host, port=port))
    return CONF_PATH


class BrokerHandle:
    """A running broker we started (or an external one we merely detected)."""

    def __init__(self, proc: subprocess.Popen | None, host: str, port: int, external: bool):
        self.proc = proc
        self.host = host
        self.port = port
        self.external = external

    def stop(self) -> None:
        if self.external or self.proc is None:
            return
        if self.proc.poll() is None:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:  # pragma: no cover
                self.proc.kill()
            log.info("Mosquitto broker stopped")

    def __enter__(self) -> "BrokerHandle":
        return self

    def __exit__(self, *exc) -> None:
        self.stop()


def start_broker(host: str = "127.0.0.1", port: int = 1883, wait_s: float = 6.0) -> BrokerHandle:
    """Ensure a broker is listening, starting one if necessary."""
    if port_open(host, port):
        log.info("Using broker already listening on %s:%d", host, port)
        return BrokerHandle(None, host, port, external=True)

    binary = mosquitto_binary()
    if binary is None:
        raise RuntimeError(
            "No MQTT broker found. Install one with `brew install mosquitto` "
            "(macOS) or `sudo apt install mosquitto` (Linux), or start a "
            "container: docker run -d -p 1883:1883 eclipse-mosquitto"
        )

    conf = write_config(host, port)
    log.info("Starting Mosquitto: %s -c %s", binary, conf)
    proc = subprocess.Popen(
        [binary, "-c", str(conf)],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True,
    )

    deadline = time.time() + wait_s
    while time.time() < deadline:
        if port_open(host, port):
            log.info("Broker ready on %s:%d (pid %d)", host, port, proc.pid)
            return BrokerHandle(proc, host, port, external=False)
        if proc.poll() is not None:
            out = proc.stdout.read() if proc.stdout else ""
            raise RuntimeError(f"Mosquitto exited immediately:\n{out}")
        time.sleep(0.15)

    proc.terminate()
    raise RuntimeError(f"Broker did not become ready on {host}:{port} within {wait_s}s")
